services:
  db:
    image: oracle-21
    container_name: oracle21
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./mock:/run/mock
    environment:
      - ORACLE_PWD=secret
      - ORACLE_CHARACTERSET=TH8TISASCII
    ports:
      - 1521:1521

volumes:
  oracle_data:
    driver: local
